version: "3.7"
services:
#  database:
#    image: mysql:5.7
#    container_name: api-lumen-mysql
#    volumes:
#      - "./docker/mysql/data/:/var/lib/mysql"
#    environment:
#      MYSQL_ROOT_PASSWORD: 123456
#      MYSQL_USER: root
#      MYSQL_PASSWORD: 123456
#      MYSQL_DATABASE: api-lumen
#    restart: always
#    networks:
#      - private-network
  php:
    build:
      dockerfile: ./Dockerfile
      context: .
    image: phpunit-githubactions-boilerplate
    restart: always
    container_name: phpunit-githubactions-boilerplate
    volumes:
      - ./application:/var/www/html
    ports:
      - "8000:8000"
#    networks:
#      - private-network
#    depends_on:
#      - database
#networks:
#  private-network:
#    name: private-network
#    driver: bridge